[package]
name = "xtask"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.66"
clap = { version = "4.0.17", features = ["derive"] }
aya-tool = { git = "https://github.com/aya-rs/aya", branch = "main" }


